### ISSUE TITLE
Issues loading Scoreboard

### ISSUE THREAD

**Issue by NiceKaleido** [VelizarBG/score-migrator#2]
Hi there,
I've encountered an issue on my 1.21 Fabric server which wiped all scoreboard data. Here's the Error from the console log.

```
[02:14:09] [Server thread/ERROR]: Error loading saved data: scoreboard
net.minecraft.class_8911: Loading NBT data
	at net.minecraft.class_2487.method_10581(class_2487.java:530) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_53889(class_2487.java:76) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_23240(class_2487.java:63) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_23262(class_2487.java:58) ~[server-intermediary.jar:?]
	at net.minecraft.class_2499$1.method_53895(class_2499.java:48) ~[server-intermediary.jar:?]
	at net.minecraft.class_2499$1.method_23249(class_2499.java:31) ~[server-intermediary.jar:?]
	at net.minecraft.class_2499$1.method_23262(class_2499.java:26) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487.method_10581(class_2487.java:524) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_53889(class_2487.java:76) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_23240(class_2487.java:63) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_23262(class_2487.java:58) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487.method_10581(class_2487.java:524) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_53889(class_2487.java:76) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_23240(class_2487.java:63) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_23262(class_2487.java:58) ~[server-intermediary.jar:?]
	at net.minecraft.class_2507.method_52892(class_2507.java:191) ~[server-intermediary.jar:?]
	at net.minecraft.class_2507.method_10626(class_2507.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_2507.method_10625(class_2507.java:111) ~[server-intermediary.jar:?]
	at net.minecraft.class_2507.method_10629(class_2507.java:51) ~[server-intermediary.jar:?]
	at net.minecraft.class_26.method_17923(class_26.java:96) ~[server-intermediary.jar:?]
	at net.minecraft.class_26.method_120(class_26.java:75) ~[server-intermediary.jar:?]
	at net.minecraft.class_26.method_20786(class_26.java:63) ~[server-intermediary.jar:?]
	at net.minecraft.class_26.method_17924(class_26.java:47) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_17976(MinecraftServer.java:326) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:380) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:342) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3823(class_3176.java:185) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:664) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:266) ~[?:?]
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:175) ~[?:?]
	at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:128) ~[?:?]
	at net.minecraft.class_6826.method_39780(class_6826.java:94) ~[server-intermediary.jar:?]
	at net.minecraft.class_6826.read(class_6826.java:47) ~[server-intermediary.jar:?]
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:208) ~[?:?]
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:594) ~[?:?]
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:550) ~[?:?]
	at net.minecraft.class_2519$1.method_53904(class_2519.java:31) ~[server-intermediary.jar:?]
	at net.minecraft.class_2519$1.method_23257(class_2519.java:19) ~[server-intermediary.jar:?]
	at net.minecraft.class_2519$1.method_23262(class_2519.java:16) ~[server-intermediary.jar:?]
	at net.minecraft.class_2499$1.method_53895(class_2499.java:48) ~[server-intermediary.jar:?]
	at net.minecraft.class_2499$1.method_23249(class_2499.java:31) ~[server-intermediary.jar:?]
	at net.minecraft.class_2499$1.method_23262(class_2499.java:26) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487.method_10581(class_2487.java:524) ~[server-intermediary.jar:?]
	... 29 more
```

**Comment by VelizarBG** [comment]
Hi, it seems that stack trace only describes what happens whenever the scoreboard file is empty, which does not help me at all to understand why it's empty in the first place.
If possible, I'd appreciate more info on how to reproduce the problem which leads to the scoreboard file being empty. Otherwise there really isn't anything I can do.

**Comment by NiceKaleido** [comment]
I wish I could tell you more but the error just appeared out of nowhere and hasn't luckily happened again.

**Comment by VelizarBG** [comment]
Ok, I'm closing the issue until more info is available.
